language: node_js
node_js:
  - "10.16"
  - "12.4"
  - "14.15"
  - "15.7"
sudo: false
cache:
  directories:
    - node_modules
before_install:
  # Configure npm
  - |
    # Skip updating shrinkwrap / lock
    npm config set shrinkwrap false
  # Update Node.js modules
  - |
    # Prune & rebuild node_modules
    if [[ -d node_modules ]]; then
      npm prune
      npm rebuild
    fi
before_scrpt:
  - |
    # Contents of node_modules
    npm -s ls ||:
script:
  - |
    # Run test script
    npm run-script test-travis
  - |
    # Run linting, if eslint exists
    npm run-script lint
after_script:
  - |
    # Upload coverage to coveralls if exists
    if [[ -e ./coverage/lcov.info ]]; then
      npm install --save-dev coveralls@2
      coveralls < ./coverage/lcov.info
    fi
